services:
  db:
    image: postgres:16
    container_name: myfitness-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: myfitness
      POSTGRES_USER: myfitness_user
      POSTGRES_PASSWORD: myfitness_pass
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
